const hre = require("hardhat");

async function main() {
  console.log("🚀 Deploying GoalStake contracts...\n");

  const [deployer] = await hre.ethers.getSigners();
  console.log("Deployer:", deployer.address);
  console.log("Balance:", hre.ethers.formatEther(await hre.ethers.provider.getBalance(deployer.address)), "ETH\n");

  // 1. Deploy GoalToken
  console.log("📦 Deploying GoalToken...");
  const GoalToken = await hre.ethers.getContractFactory("GoalToken");
  const goalToken = await GoalToken.deploy();
  await goalToken.waitForDeployment();
  const tokenAddress = await goalToken.getAddress();
  console.log("   GoalToken deployed to:", tokenAddress);

  // 2. Deploy FriendCircle
  console.log("📦 Deploying FriendCircle...");
  const FriendCircle = await hre.ethers.getContractFactory("FriendCircle");
  const friendCircle = await FriendCircle.deploy();
  await friendCircle.waitForDeployment();
  const circleAddress = await friendCircle.getAddress();
  console.log("   FriendCircle deployed to:", circleAddress);

  // 3. Deploy GoalMarket
  console.log("📦 Deploying GoalMarket...");
  const GoalMarket = await hre.ethers.getContractFactory("GoalMarket");
  const goalMarket = await GoalMarket.deploy(tokenAddress, circleAddress);
  await goalMarket.waitForDeployment();
  const marketAddress = await goalMarket.getAddress();
  console.log("   GoalMarket deployed to:", marketAddress);

  // 4. Authorize GoalMarket as a minter
  console.log("\n🔑 Authorizing GoalMarket as token minter...");
  await goalToken.authorizeMinter(marketAddress);
  console.log("   Done!");

  // Summary
  console.log("\n" + "═".repeat(50));
  console.log("  ✅ DEPLOYMENT COMPLETE");
  console.log("═".repeat(50));
  console.log(`  GoalToken:    ${tokenAddress}`);
  console.log(`  FriendCircle: ${circleAddress}`);
  console.log(`  GoalMarket:   ${marketAddress}`);
  console.log("═".repeat(50));

  // Write addresses to .env file for backend
  const fs = require("fs");
  const envContent = `
# Contract Addresses (auto-generated by deploy script)
GOAL_TOKEN_ADDRESS=${tokenAddress}
FRIEND_CIRCLE_ADDRESS=${circleAddress}
GOAL_MARKET_ADDRESS=${marketAddress}
`;

  fs.writeFileSync("./backend/.env.contracts", envContent.trim());
  console.log("\n📝 Contract addresses written to backend/.env.contracts");
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
